[package]
name = "telegram-quiz-bot"
version = "0.1.0"
authors = ["Andrey Manzharov <andreyrmg@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
hyper-tls = "0.4"
tokio = { version = "0.2", features = ["full"] }
